<?php
return array (
  'site' => 'http://weizhuan.gouso.com',
  'sharesite' => 'weizhuan.gouso.com',
  'ti' => '30',
  'p1' => '',
  'pp' => '',
  'song' => '0.5',
  'openreg' => '1',
  'sitename' => '够搜微赚',
  'kou_pr' => '20',
  'kou_day' => '3',
  'kou_hour' => '1,2,3,7,20',
  'yunpian' => '',
  'safe' => '1',
  'qqkf' => '34651529',
  'tc' => '10',
  'iphour' => '',
  'fangwen' => '3',
  'area' => '全国',
  'city' => '地区',
  'weixin_reg' => '0',
  'daysong' => '0.02',
  'ipreg2' => '0',
  'reg_yzr1' => '0.5',
  'gotimes' => '',
);
?>