<?php
	$b_table="addata,admindata,article,koudata,newsdata,refererdata,txdata,typedata,userdata";
	$tb[addata]=1;
$tb[admindata]=1;
$tb[article]=8;
$tb[koudata]=1;
$tb[newsdata]=1;
$tb[refererdata]=1;
$tb[txdata]=1;
$tb[typedata]=1;
$tb[userdata]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="evmiaocomadmin";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	$b_bakdatatype=0;
	?>