<?php
if(file_exists("./header.class.php")){
    include_once("./header.class.php");
}else{
    exit('header.class.php is not exists');
}
$header = ResponseHeader::getInstance();
$header->setCacheByLastModify(100);
?>
<meta charset='utf-8' />
<ul>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
	<li>我阿杜说分开啊哈的覅哦</li>
</ul>