<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
$GEN_DIR = realpath(dirname(__FILE__).'/../..').'/gen-php';
require_once $GEN_DIR.'/tutorial/tutorial_types.php';
error_reporting(E_ALL);


$GLOBALS['tutorial_CONSTANTS'] = array();

$GLOBALS['tutorial_CONSTANTS']['INT32CONSTANT'] = 9853;

$GLOBALS['tutorial_CONSTANTS']['MAPCONSTANT'] = array(
  "hello" => "world",
  "goodnight" => "moon",
);

?>
