<div class="post">
	<p class="meta"><span class="date">Sunday, April 26, 2009</span> 7:27 AM Posted by <a href="http://www.865171.cn/">Someone</a></p>
	<h2 class="title"><a href="http://www.865171.cn/">Welcome to Assiduous  </a></h2>
	<div class="entry">
		<p>This is <strong>Assiduous  </strong>, a free, fully standards-compliant CSS template designed by <a href="http://www.865171.cn/">www.865171.cn</a>, released for free under the <a href="http://www.865171.cn/">Creative Commons Attribution 2.5</a> license.  You're free to use this template for anything as long as you link back to <a href="http://www.865171.cn/">my site</a>. Enjoy :)</p>
		<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. </p>
	</div>
</div>

<div class="post">
	<p class="meta"><span class="date">Sunday, April 26, 2009</span> 7:27 AM Posted by <a href="http://www.865171.cn/">Someone</a></p>
	<h2 class="title"><a href="http://www.865171.cn/">Lorem ipsum sed aliquam</a></h2>
	<div class="entry">
		<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec   consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="http://www.865171.cn/">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros.</p>
	</div>
</div>

<div class="post">
	<p class="meta"><span class="date">Sunday, April 26, 2009</span> 7:27 AM Posted by <a href="http://www.865171.cn/">Someone</a></p>
	<h2 class="title"><a href="http://www.865171.cn/">Lorem ipsum sed aliquam</a></h2>
	<div class="entry">
		<p>Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="http://www.865171.cn/">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. </p>
	</div>
</div>