<div id="header">
	<div id="menu">
		<ul>
			<li><a href="http://www.865171.cn/" class="first">Home</a></li>
			<li class="current_page_item"><a href="http://www.865171.cn/">Blog</a></li>
			<li><a href="http://www.865171.cn/">About</a></li>
			<li><a href="http://www.865171.cn/">Contact</a></li>
		</ul>
	</div>
	<!-- end #menu -->
	<div id="search">
		<form method="get" action="">
			<fieldset>
				<input type="text" name="s" id="search-text" size="15" />
				<input type="submit" id="search-submit" value="GO" />
			</fieldset>
		</form>
	</div>
	<!-- end #search -->
</div>