<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Assiduous   by www.865171.cn</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="./css/style.css" rel="stylesheet" type="text/css" media="screen" />
<script src='./js/jquery-2.1.4.min.js'></script>
<script src='./js/function.js'></script>
</head>
<body>

<div id="header-wrapper"></div>

<div id="logo"></div>

<hr />

<div id="page">
	<div id="page-bgtop">
		<div id="content"></div>

		<div id="sidebar"></div>

		<div style="clear: both;">&nbsp;</div>
	</div>

	<div id="footer"></div>
</div>
</body>
</html>
