<ul>
	<li>
		<h2>Aliquam tempus</h2>
		<p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, volutpat.</p>
	</li>
	<li>
		<h2>Pellenteque ornare </h2>
		<ul>
			<?php if(isset($sidebars) && !empty($sidebars)): ?>
			<?php foreach($sidebars as $sidebar): ?>
			<li><a href="javascript:void(0)"><?php echo $sidebar; ?></a></li>
			<?php endforeach; ?>
			<?php endif; ?>
		</ul>
	</li>
	<li>
		<h2>Turpis nulla</h2>
		<ul>
			<li><a href="http://www.865171.cn/">Nec metus sed donec</a></li>
			<li><a href="http://www.865171.cn/">Magna lacus bibendum mauris</a></li>
			<li><a href="http://www.865171.cn/">Velit semper nisi molestie</a></li>
			<li><a href="http://www.865171.cn/">Eget tempor eget nonummy</a></li>
			<li><a href="http://www.865171.cn/">Nec metus sed donec</a></li>
			<li><a href="http://www.865171.cn/">Nec metus sed donec</a></li>
			<li><a href="http://www.865171.cn/">Magna lacus bibendum mauris</a></li>
			<li><a href="http://www.865171.cn/">Velit semper nisi molestie</a></li>
			<li><a href="http://www.865171.cn/">Eget tempor eget nonummy</a></li>
			<li><a href="http://www.865171.cn/">Nec metus sed donec</a></li>
		</ul>
	</li>
</ul>
